"use client";

import { FormEvent, useMemo, useState } from "react";
import { getService, Locale, services } from "../lib/catalog";

type Navigation = { matches: { serviceId: string; probability: number }[]; primaryServiceId: string | "none"; needsClarification: boolean; clarification: "passport" | "license" | "vehicle" | null; urgency: boolean; source: "typesafe" | "demo"; responseLatencyMs: number };
const copy = {
  es: { badge:"Buscador de servicios", title:<>Encuentra tu <em>trámite.</em></>, lede:"Busca servicios oficiales de Boston, Massachusetts y el gobierno federal.", placeholder:"Ej. renovar licencia, permiso de estacionamiento, acta de nacimiento", search:"Buscar", searching:"Buscando…", results:"Resultados", noResults:"No encontramos una ruta clara.", clarify:"Prueba con renovar, reemplazar, primer pasaporte o permiso de estacionamiento.", official:"Abrir sitio oficial", requirements:"Ver requisitos", next:"Siguiente paso", verified:"Verificado", live:"TypeSafe", demo:"Modo demo", privacy:"No guardamos tu búsqueda ni datos personales.", lang:"English", error:"No se pudo completar la búsqueda. Inténtalo otra vez.", resultCount:"resultados oficiales", oneResult:"resultado oficial", suggestions:"Sugerencias", didYouMean:"¿Quisiste buscar…?", urgent:"Parece que tienes poco tiempo. Confirma los plazos y opciones directamente en la fuente oficial.", passportQuestion:"¿Es tu primer pasaporte o una renovación?", licenseQuestion:"¿Necesitas una primera licencia, renovación o reemplazo?", vehicleQuestion:"¿Es un registro nuevo o una renovación?", first:"Primer trámite", renewal:"Renovación", replacement:"Reemplazo", newRegistration:"Registro nuevo" },
  en: { badge:"Service search", title:<>Find your <em>government service.</em></>, lede:"Search official Boston, Massachusetts, and federal services.", placeholder:"Example: renew license, parking permit, birth certificate", search:"Search", searching:"Searching…", results:"Results", noResults:"We could not find a clear route.", clarify:"Try renew, replace, first passport, or parking permit.", official:"Open official site", requirements:"View requirements", next:"Next action", verified:"Verified", live:"TypeSafe", demo:"Demo mode", privacy:"We do not save your search or personal data.", lang:"Español", error:"We could not complete the search. Try again.", resultCount:"official results", oneResult:"official result", suggestions:"Suggestions", didYouMean:"Did you mean…?", urgent:"It sounds time-sensitive. Confirm timelines and options directly with the official source.", passportQuestion:"Is this your first passport or a renewal?", licenseQuestion:"Do you need a first license, renewal, or replacement?", vehicleQuestion:"Is this a new registration or renewal?", first:"First time", renewal:"Renewal", replacement:"Replacement", newRegistration:"New registration" },
} as const;

export default function Home() {
  const [locale, setLocale] = useState<Locale>("es"); const [query, setQuery] = useState(""); const [navigation, setNavigation] = useState<Navigation | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const t = copy[locale];
  const results = useMemo(() => navigation?.matches.map((match) => getService(match.serviceId)).filter((service): service is NonNullable<ReturnType<typeof getService>> => Boolean(service)) ?? [], [navigation]);
  const suggestions = useMemo(() => { const words = query.toLocaleLowerCase().split(/\s+/).filter((word) => word.length > 2); if (!words.length) return []; return services.filter((service) => { const searchable = [service.copy[locale].title, ...service.keywords].join(" ").toLocaleLowerCase(); return words.some((word) => searchable.includes(word)); }).slice(0, 5); }, [locale, query]);
  async function runSearch(term: string) { if (!term.trim()) return; setLoading(true); setError(""); try { const response = await fetch("/api/interpret", { method:"POST", headers:{ "Content-Type":"application/json" }, body:JSON.stringify({ message:term }) }); const body = await response.json() as Navigation & { error?:string }; if (!response.ok) throw new Error(body.error ?? t.error); setNavigation(body); if (body.needsClarification && term.length <= 90 && !/@|\d{7,}/.test(term)) { const previous = JSON.parse(localStorage.getItem("thiscita-unresolved-v1") ?? "[]") as string[]; localStorage.setItem("thiscita-unresolved-v1", JSON.stringify([...new Set([...previous, term])].slice(-30))); } } catch (cause) { setError(cause instanceof Error ? cause.message : t.error); } finally { setLoading(false); } }
  function search(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void runSearch(query); }
  return <main><header className="masthead"><a className="brand" href="/"><span>OBRA</span><i>β</i></a><span className="demo-tag">Módulo 01 · {t.badge}</span><button className="language" type="button" onClick={() => setLocale(locale === "es" ? "en" : "es")}>{t.lang}</button></header>
    <section className="search-hero" id="search"><p className="kicker"><span />{t.badge}</p><h1>{t.title}</h1><p>{t.lede}</p><form className="search-box" onSubmit={search}><label className="sr-only" htmlFor="service-search">{t.badge}</label><span aria-hidden="true">⌕</span><input id="service-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.placeholder} /><button type="submit" disabled={loading}>{loading ? t.searching : t.search}</button></form>{suggestions.length > 0 && <div className="suggestions"><span>{t.suggestions}</span>{suggestions.map((service) => <button type="button" key={service.id} onClick={() => { setQuery(service.copy[locale].title); void runSearch(service.copy[locale].title); }}>{service.copy[locale].title}</button>)}</div>}<small>{t.privacy}</small>{error && <p className="error" role="alert">{error}</p>}</section>
    {navigation && <section className="results" aria-live="polite"><div className="results-head"><div><h2>{t.results}</h2><p>{results.length} {results.length === 1 ? t.oneResult : t.resultCount}</p></div><span className={navigation.source === "typesafe" ? "source live" : "source"}>{navigation.source === "typesafe" ? t.live : t.demo} · {navigation.responseLatencyMs} ms</span></div>{navigation.urgency && <p className="urgency">{t.urgent}</p>}{navigation.needsClarification && navigation.clarification && <div className="clarification"><strong>{navigation.clarification === "passport" ? t.passportQuestion : navigation.clarification === "license" ? t.licenseQuestion : t.vehicleQuestion}</strong><div>{(navigation.clarification === "license" || navigation.clarification === "passport") && <button type="button" onClick={() => { const term = `${query} ${t.first}`; setQuery(term); void runSearch(term); }}>{t.first}</button>}<button type="button" onClick={() => { const term = `${query} ${t.renewal}`; setQuery(term); void runSearch(term); }}>{t.renewal}</button>{navigation.clarification === "license" && <button type="button" onClick={() => { const term = `${query} ${t.replacement}`; setQuery(term); void runSearch(term); }}>{t.replacement}</button>}{navigation.clarification === "vehicle" && <button type="button" onClick={() => { const term = `${query} ${t.newRegistration}`; setQuery(term); void runSearch(term); }}>{t.newRegistration}</button>}</div></div>}{navigation.needsClarification || results.length === 0 ? <div className="empty-result"><strong>{t.noResults}</strong><p>{t.clarify}</p>{suggestions.length > 0 && <div className="did-you-mean"><span>{t.didYouMean}</span>{suggestions.map((service) => <button type="button" key={service.id} onClick={() => { setQuery(service.copy[locale].title); void runSearch(service.copy[locale].title); }}>{service.copy[locale].title}</button>)}</div>}</div> : <div className="result-list">{results.map((service) => { const item = service.copy[locale]; return <article className="result-card" key={service.id}><div className="result-meta"><span>{service.authority}</span><small>{service.authorityName}</small></div><h3>{item.title}</h3><div className="next-action"><strong>{t.next}</strong><p>{item.nextAction}</p></div><details><summary>{t.requirements}</summary><ul>{item.requirements.map((requirement) => <li key={requirement}>{requirement}</li>)}</ul></details><footer><a href={service.officialUrl} target="_blank" rel="noreferrer">{t.official} ↗</a><small>{t.verified}: {service.lastVerified}</small></footer></article>; })}</div>}</section>}
  </main>;
}
