export const copy = {
  es: {
    back: "Inicio",
    badge: "Revisor de propuestas",
    title: (
      <>
        Revisa, compara y <em>decide.</em>
      </>
    ),
    lede: "Analiza una propuesta o compara una nueva versión antes de enviarla.",
    originalLabel: "Propuesta original",
    revisionLabel: "Versión revisada",
    originalHint: "El análisis comienza al subirla.",
    revisionHint: "Opcional · activa la comparación",
    formats: "PDF, DOCX o TXT · Máximo 25 MB",
    choose: "Elegir documento",
    change: "Cambiar",
    remove: "Quitar versión",
    analyzing: "Analizando…",
    complete: "Análisis listo",
    private: "Los archivos se procesan para este análisis y no se guardan.",
    result: "Revisión comercial",
    waiting: "Esperando la propuesta original",
    ready: "Lista para revisión final",
    review: "Necesita revisión",
    readiness: "Preparación para enviar",
    improvement: "Cambio de preparación",
    original: "Original",
    revision: "Revisada",
    summary: "Resumen",
    summaryNote: "Extractos del documento",
    viewEvidence: "Ver evidencia",
    noEvidence: "No se seleccionó un fragmento exacto.",
    evidence: "Evidencia exacta",
    clear: "Claro",
    standby: "En espera",
    missing: "Falta información",
    needsReview: "Revisar",
    legal: "No es asesoría legal ni determina la validez de un contrato.",
    live: "TypeSafe",
    demo: "Modo demo",
    error: "No se pudo analizar el documento.",
    changes: {
      unchanged: "Sin cambio",
      added: "Añadido",
      removed: "Eliminado",
      modified: "Modificado",
      unclear: "No concluyente",
    },
    checks: {
      scope: [
        "Alcance",
        "Confirma entregables, exclusiones y criterios de aceptación.",
      ],
      pricing: [
        "Precio y pago",
        "Confirma precio, calendario de cobro y condiciones de pago.",
      ],
      timeline: ["Fechas", "Confirma fechas, dependencias y responsables."],
      nonStandardCommitment: [
        "Compromisos",
        "Revisa garantías, soporte ilimitado, exclusividad o compromisos sin límite.",
      ],
    },
  },
  en: {
    back: "Home",
    badge: "Proposal review",
    title: (
      <>
        Review, compare, and <em>decide.</em>
      </>
    ),
    lede: "Analyze one proposal or compare a revised version before sending it.",
    originalLabel: "Original proposal",
    revisionLabel: "Revised version",
    originalHint: "Analysis starts when you upload it.",
    revisionHint: "Optional · enables comparison",
    formats: "PDF, DOCX, or TXT · 25 MB maximum",
    choose: "Choose document",
    change: "Change",
    remove: "Remove version",
    analyzing: "Analyzing…",
    complete: "Analysis ready",
    private: "Files are processed for this analysis and are not stored.",
    result: "Commercial review",
    waiting: "Waiting for the original proposal",
    ready: "Ready for final review",
    review: "Needs review",
    readiness: "Readiness to send",
    improvement: "Readiness change",
    original: "Original",
    revision: "Revised",
    summary: "Summary",
    summaryNote: "Document excerpts",
    viewEvidence: "View evidence",
    noEvidence: "No exact passage was selected.",
    evidence: "Exact evidence",
    clear: "Clear",
    standby: "Standby",
    missing: "Missing information",
    needsReview: "Review",
    legal: "This is not legal advice and does not determine contract validity.",
    live: "TypeSafe",
    demo: "Demo mode",
    error: "The document could not be analyzed.",
    changes: {
      unchanged: "Unchanged",
      added: "Added",
      removed: "Removed",
      modified: "Modified",
      unclear: "Unclear",
    },
    checks: {
      scope: [
        "Scope",
        "Confirm deliverables, exclusions, and acceptance criteria.",
      ],
      pricing: [
        "Pricing & payment",
        "Confirm price, billing schedule, and payment terms.",
      ],
      timeline: ["Timeline", "Confirm dates, dependencies, and owners."],
      nonStandardCommitment: [
        "Commitments",
        "Review guarantees, unlimited support, exclusivity, or uncapped commitments.",
      ],
    },
  },
} as const;

export type ProposalCopy = (typeof copy)[keyof typeof copy];
